import { Academy, Coach, Slot, Enrollment, TransitSession } from '@sportnexus/types'

export const MOCK_COACHES: Coach[] = [
  { id: 'coach1', academyId: 'academy_champions', name: 'Ravi Kumar', photo: 'https://i.pravatar.cc/80?img=11', sportTags: ['Cricket'], experienceYears: 12, bio: 'Former Ranji Trophy player with 12 years coaching experience.', certifications: ['BCCI Level 2'], isActive: true },
  { id: 'coach2', academyId: 'academy_champions', name: 'Suresh Reddy', photo: 'https://i.pravatar.cc/80?img=12', sportTags: ['Cricket'], experienceYears: 8, bio: 'Specialist batting coach.', certifications: ['BCCI Level 1'], isActive: true },
  { id: 'coach3', academyId: 'academy_kickstart', name: 'Arjun Sharma', photo: 'https://i.pravatar.cc/80?img=13', sportTags: ['Football'], experienceYears: 10, bio: 'AFC certified football coach.', certifications: ['AFC B License'], isActive: true },
]

export const MOCK_SLOTS: Slot[] = [
  { id: 'slot1', programId: 'prog1', timeStart: '06:30', timeEnd: '07:30', daysOfWeek: ['Monday', 'Wednesday', 'Friday'], totalCapacity: 20, enrolledCount: 12, isActive: true },
  { id: 'slot2', programId: 'prog1', timeStart: '07:30', timeEnd: '08:30', daysOfWeek: ['Tuesday', 'Thursday', 'Saturday'], totalCapacity: 20, enrolledCount: 8, isActive: true },
  { id: 'slot3', programId: 'prog1', timeStart: '17:00', timeEnd: '18:00', daysOfWeek: ['Monday', 'Wednesday', 'Friday'], totalCapacity: 20, enrolledCount: 18, isActive: true },
  { id: 'slot4', programId: 'prog1', timeStart: '18:00', timeEnd: '19:00', daysOfWeek: ['Tuesday', 'Thursday', 'Saturday'], totalCapacity: 20, enrolledCount: 5, isActive: true },
]

export const MOCK_ACADEMIES: Academy[] = [
  {
    id: 'academy_champions',
    name: 'Champions Cricket Academy',
    description: 'Premier cricket training facility in Hyderabad with BCCI-certified coaches.',
    address: '12, Road No. 5, Banjara Hills, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4156,
    lng: 78.4347,
    rating: 4.8,
    reviewCount: 124,
    transportAvailable: true,
    isVerified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    distance: 1.2,
    photos: [{ id: 'p1', academyId: 'academy_champions', url: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800', isPrimary: true }],
    programs: [{ id: 'prog1', academyId: 'academy_champions', sportType: 'Cricket', name: 'Junior Cricket', feeMonthly: 2500, ageGroupMin: 8, ageGroupMax: 14, durationMonths: 3, isActive: true, createdAt: '2024-01-01T00:00:00Z' }],
  },
  {
    id: 'academy_kickstart',
    name: 'KickStart Football Club',
    description: 'AFC-affiliated football academy offering structured training programs.',
    address: '45, Hitech City Road, Madhapur, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4432,
    lng: 78.3773,
    rating: 4.6,
    reviewCount: 89,
    transportAvailable: true,
    isVerified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    distance: 2.8,
    photos: [{ id: 'p2', academyId: 'academy_kickstart', url: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800', isPrimary: true }],
    programs: [{ id: 'prog2', academyId: 'academy_kickstart', sportType: 'Football', name: 'Football U-12', feeMonthly: 2000, ageGroupMin: 6, ageGroupMax: 12, durationMonths: 3, isActive: true, createdAt: '2024-01-01T00:00:00Z' }],
  },
  {
    id: 'academy_aquazone',
    name: 'AquaZone Swimming Centre',
    description: 'Olympic-length pool with heated water and SAI-certified coaches.',
    address: '8, Jubilee Hills Check Post, Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4337,
    lng: 78.4076,
    rating: 4.9,
    reviewCount: 213,
    transportAvailable: false,
    isVerified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    distance: 3.5,
    photos: [{ id: 'p3', academyId: 'academy_aquazone', url: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800', isPrimary: true }],
    programs: [{ id: 'prog3', academyId: 'academy_aquazone', sportType: 'Swimming', name: 'Beginner Swimming', feeMonthly: 2800, ageGroupMin: 4, ageGroupMax: 60, durationMonths: 1, isActive: true, createdAt: '2024-01-01T00:00:00Z' }],
  },
  {
    id: 'academy_courtside',
    name: 'CourtSide Racquet Academy',
    description: '4 international-standard tennis and badminton courts.',
    address: '22, DLF Cybercity, Gachibowli, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4429,
    lng: 78.3489,
    rating: 4.5,
    reviewCount: 67,
    transportAvailable: true,
    isVerified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    distance: 5.1,
    photos: [{ id: 'p4', academyId: 'academy_courtside', url: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800', isPrimary: true }],
    programs: [{ id: 'prog4', academyId: 'academy_courtside', sportType: 'Tennis', name: 'Junior Tennis', feeMonthly: 3000, ageGroupMin: 6, ageGroupMax: 16, durationMonths: 3, isActive: true, createdAt: '2024-01-01T00:00:00Z' }],
  },
  {
    id: 'academy_allstars',
    name: 'AllStars Multi-Sport Hub',
    description: 'Multi-discipline sports complex with cricket, football, basketball and athletics.',
    address: '56, Kondapur Main Road, Kondapur, Hyderabad',
    city: 'Hyderabad',
    lat: 17.4598,
    lng: 78.3523,
    rating: 4.7,
    reviewCount: 156,
    transportAvailable: false,
    isVerified: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    distance: 6.3,
    photos: [{ id: 'p5', academyId: 'academy_allstars', url: 'https://images.unsplash.com/photo-1546519638492-4827eff40467?w=800', isPrimary: true }],
    programs: [{ id: 'prog5', academyId: 'academy_allstars', sportType: 'Basketball', name: 'Basketball Training', feeMonthly: 2200, ageGroupMin: 10, ageGroupMax: 30, durationMonths: 3, isActive: true, createdAt: '2024-01-01T00:00:00Z' }],
  },
]
